export default [
    {
        "name": "Abbey Mortgage Bank",
        "slug": "abbey-mortgage-bank",
        "code": "801",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 174,
    },
    {
        "name": "Access Bank",
        "slug": "access-bank",
        "code": "044",
        "longcode": "044150149",
        "gateway": "emandate",
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 1,
    },
    {
        "name": "Access Bank (Diamond)",
        "slug": "access-bank-diamond",
        "code": "063",
        "longcode": "063150162",
        "gateway": "emandate",
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 3,
    },
    {
        "name": "ALAT by WEMA",
        "slug": "alat-by-wema",
        "code": "035A",
        "longcode": "035150103",
        "gateway": "emandate",
        "pay_with_bank": true,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 27,
    },
    {
        "name": "ASO Savings and Loans",
        "slug": "asosavings",
        "code": "401",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 63,
    },
    {
        "name": "Bowen Microfinance Bank",
        "slug": "bowen-microfinance-bank",
        "code": "50931",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 108,
    },
    {
        "name": "CEMCS Microfinance Bank",
        "slug": "cemcs-microfinance-bank",
        "code": "50823",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 74,
    },
    {
        "name": "Citibank Nigeria",
        "slug": "citibank-nigeria",
        "code": "023",
        "longcode": "023150005",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 2,
    },
    {
        "name": "Coronation Merchant Bank",
        "slug": "coronation-merchant-bank",
        "code": "559",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 173,
    },
    {
        "name": "Ecobank Nigeria",
        "slug": "ecobank-nigeria",
        "code": "050",
        "longcode": "050150010",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 4,
    },
    {
        "name": "Ekondo Microfinance Bank",
        "slug": "ekondo-microfinance-bank",
        "code": "562",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 64,
    },
    {
        "name": "Eyowo",
        "slug": "eyowo",
        "code": "50126",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 167,
    },
    {
        "name": "Fidelity Bank",
        "slug": "fidelity-bank",
        "code": "070",
        "longcode": "070150003",
        "gateway": "emandate",
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 6,
    },
    {
        "name": "First Bank of Nigeria",
        "slug": "first-bank-of-nigeria",
        "code": "011",
        "longcode": "011151003",
        "gateway": "ibank",
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 7,
    },
    {
        "name": "First City Monument Bank",
        "slug": "first-city-monument-bank",
        "code": "214",
        "longcode": "214150018",
        "gateway": "emandate",
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 8,
    },
    {
        "name": "FSDH Merchant Bank Limited",
        "slug": "fsdh-merchant-bank-limited",
        "code": "501",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 112,
    },
    {
        "name": "Globus Bank",
        "slug": "globus-bank",
        "code": "00103",
        "longcode": "103015001",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 70,
    },
    {
        "name": "Guaranty Trust Bank",
        "slug": "guaranty-trust-bank",
        "code": "058",
        "longcode": "058152036",
        "gateway": "ibank",
        "pay_with_bank": true,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 9,
    },
    {
        "name": "Hackman Microfinance Bank",
        "slug": "hackman-microfinance-bank",
        "code": "51251",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 111,
    },
    {
        "name": "Hasal Microfinance Bank",
        "slug": "hasal-microfinance-bank",
        "code": "50383",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 81,
    },
    {
        "name": "Heritage Bank",
        "slug": "heritage-bank",
        "code": "030",
        "longcode": "030159992",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 10,
    },
    {
        "name": "Ibile Microfinance Bank",
        "slug": "ibile-mfb",
        "code": "51244",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 168,
    },
    {
        "name": "Infinity MFB",
        "slug": "infinity-mfb",
        "code": "50457",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 172,
    },
    {
        "name": "Jaiz Bank",
        "slug": "jaiz-bank",
        "code": "301",
        "longcode": "301080020",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 22,
    },
    {
        "name": "Keystone Bank",
        "slug": "keystone-bank",
        "code": "082",
        "longcode": "082150017",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 11,
    },
    {
        "name": "Kuda Bank",
        "slug": "kuda-bank",
        "code": "50211",
        "longcode": "",
        "gateway": "digitalbankmandate",
        "pay_with_bank": true,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 67,
    },
    {
        "name": "Lagos Building Investment Company Plc.",
        "slug": "lbic-plc",
        "code": "90052",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 109,
    },
    {
        "name": "One Finance",
        "slug": "one-finance",
        "code": "565",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 82,
    },
    {
        "name": "PalmPay",
        "slug": "palmpay",
        "code": "999991",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 169,
    },
    {
        "name": "Parallex Bank",
        "slug": "parallex-bank",
        "code": "526",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 26,
    },
    {
        "name": "Parkway - ReadyCash",
        "slug": "parkway-ready-cash",
        "code": "311",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 110,
    },
    {
        "name": "Paycom",
        "slug": "paycom",
        "code": "999992",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 171,
    },
    {
        "name": "Petra Mircofinance Bank Plc",
        "slug": "petra-microfinance-bank-plc",
        "code": "50746",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 170,
    },
    {
        "name": "Polaris Bank",
        "slug": "polaris-bank",
        "code": "076",
        "longcode": "076151006",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 13,
    },
    {
        "name": "Providus Bank",
        "slug": "providus-bank",
        "code": "101",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 25,
    },
    {
        "name": "Rubies MFB",
        "slug": "rubies-mfb",
        "code": "125",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 69,
    },
    {
        "name": "Sparkle Microfinance Bank",
        "slug": "sparkle-microfinance-bank",
        "code": "51310",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 72,
    },
    {
        "name": "Stanbic IBTC Bank",
        "slug": "stanbic-ibtc-bank",
        "code": "221",
        "longcode": "221159522",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 14,
    },
    {
        "name": "Standard Chartered Bank",
        "slug": "standard-chartered-bank",
        "code": "068",
        "longcode": "068150015",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 15,
    },
    {
        "name": "Sterling Bank",
        "slug": "sterling-bank",
        "code": "232",
        "longcode": "232150016",
        "gateway": "emandate",
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 16,
    },
    {
        "name": "Suntrust Bank",
        "slug": "suntrust-bank",
        "code": "100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 23,
    },
    {
        "name": "TAJ Bank",
        "slug": "taj-bank",
        "code": "302",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 68,
    },
    {
        "name": "TCF MFB",
        "slug": "tcf-mfb",
        "code": "51211",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 75,
    },
    {
        "name": "Titan Bank",
        "slug": "titan-bank",
        "code": "102",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 73,
    },
    {
        "name": "Union Bank of Nigeria",
        "slug": "union-bank-of-nigeria",
        "code": "032",
        "longcode": "032080474",
        "gateway": "emandate",
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 17,
    },
    {
        "name": "United Bank For Africa",
        "slug": "united-bank-for-africa",
        "code": "033",
        "longcode": "033153513",
        "gateway": "emandate",
        "pay_with_bank": true,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 18,
    },
    {
        "name": "Unity Bank",
        "slug": "unity-bank",
        "code": "215",
        "longcode": "215154097",
        "gateway": "emandate",
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 19,
    },
    {
        "name": "VFD Microfinance Bank Limited",
        "slug": "vfd",
        "code": "566",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": false,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 71,
    },
    {
        "name": "Wema Bank",
        "slug": "wema-bank",
        "code": "035",
        "longcode": "035150103",
        "gateway": null,
        "pay_with_bank": false,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 20,
    },
    {
        "name": "Zenith Bank",
        "slug": "zenith-bank",
        "code": "057",
        "longcode": "057150013",
        "gateway": "emandate",
        "pay_with_bank": true,
        "active": true,
        "is_deleted": null,
        "country": "Nigeria",
        "currency": "NGN",
        "type": "nuban",
        "id": 21,
    }
]